import os




SECRET_KEY = os.getenv("DASHBOARD_SECRET_KEY")
ACCESS_TOKEN = os.getenv("DASHBOARD_ACCESS_TOKEN")
SESSION_EXPIRY_HOURS = 24


SMTP_HOST = "smtp.gmail.com"
SMTP_PORT = 587
SMTP_USER = "support@metricord.app"
SMTP_PASSWORD = os.getenv("SMTP_PASSWORD")  
SMTP_FROM = "Metricord Dashboard <support@metricord.app>"


ALLOWED_EMAIL_DOMAIN = "@metricord.app"
OTP_LENGTH = 6
OTP_EXPIRY_SECONDS = 300
OTP_MAX_ATTEMPTS = 5
OTP_RATE_LIMIT = 3


DISCORD_CLIENT_ID = "1462004084302151814"
DISCORD_CLIENT_SECRET = os.getenv("DISCORD_CLIENT_SECRET")
DISCORD_REDIRECT_URI = "http://207.180.223.191:8092/auth/callback"


ADMIN_USER_IDS = [471218810964410368]  
BOT_TOKEN = os.getenv("BOT_TOKEN")
